// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxclichatcore.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Registers one tool on an MCP server, taking the microflow as a plain string.
 * Schema is left null on purpose: AddTool derives the tool's JSON schema from
 * the executing microflow's parameters when none is supplied.
 * @param $McpServerObject the server returned by JA_McpServer_Create
 * @param $ToolName tool name as the model will see it (no spaces)
 * @param $Description what the tool does — this is the model's only guidance
 * @param $ExecutingMicroflow qualified name of the microflow to run
 * @returns true once the tool is registered
 */
public class JA_McpServer_AddTool extends UserAction<java.lang.Boolean>
{
	/** @deprecated use McpServerObject.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __McpServerObject;
	private final mcpserver.proxies.McpServer McpServerObject;
	private final java.lang.String ToolName;
	private final java.lang.String Description;
	private final java.lang.String ExecutingMicroflow;

	public JA_McpServer_AddTool(
		IContext context,
		IMendixObject _mcpServerObject,
		java.lang.String _toolName,
		java.lang.String _description,
		java.lang.String _executingMicroflow
	)
	{
		super(context);
		this.__McpServerObject = _mcpServerObject;
		this.McpServerObject = _mcpServerObject == null ? null : mcpserver.proxies.McpServer.initialize(getContext(), _mcpServerObject);
		this.ToolName = _toolName;
		this.Description = _description;
		this.ExecutingMicroflow = _executingMicroflow;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

		new mcpserver.actions.AddTool(
		        getContext(),
		        McpServerObject.getMendixObject(),
		        ToolName,
		        Description,
		        ExecutingMicroflow,
		        null
		).executeAction();
		return true;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_McpServer_AddTool";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
