// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxclichatcore.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Creates the MCP server, taking the authentication microflow as a plain string.
 * @param $Path root path the server is served under, e.g. 'memory'
 * @param $ServerName server name reported to clients ('mcp' and 'sse' are reserved)
 * @param $Version server version reported to clients
 * @param $ProtocolVersion MCP protocol version enum name, e.g. 'v2025_03_26'
 * @param $AuthenticationMicroflow qualified name of the authorization microflow
 * @returns the created server, to pass to JA_McpServer_AddTool
 */
public class JA_McpServer_Create extends UserAction<IMendixObject>
{
	private final java.lang.String Path;
	private final java.lang.String ServerName;
	private final java.lang.String Version;
	private final java.lang.String ProtocolVersion;
	private final java.lang.String AuthenticationMicroflow;

	public JA_McpServer_Create(
		IContext context,
		java.lang.String _path,
		java.lang.String _serverName,
		java.lang.String _version,
		java.lang.String _protocolVersion,
		java.lang.String _authenticationMicroflow
	)
	{
		super(context);
		this.Path = _path;
		this.ServerName = _serverName;
		this.Version = _version;
		this.ProtocolVersion = _protocolVersion;
		this.AuthenticationMicroflow = _authenticationMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		// The original action's Java constructor takes the microflow as a String, so the
		// model-level Microflow parameter type is bypassed entirely.
		return new mcpserver.actions.CreateMCPServer(
		        getContext(),
		        Path,
		        ServerName,
		        Version,
		        ProtocolVersion,
		        AuthenticationMicroflow
		).executeAction();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_McpServer_Create";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
