// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxclichatagent.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * The second instance of the microflow-typed-parameter problem (FINDINGS 36).
 * AgentCommons.ChatContext_Create_ForAgent takes ActionMicroflow, which is
 * microflow-typed in the model, so calling it from MDL fails the same way the
 * MCP Server module's actions did:
 * [CE0115] "The arguments that are passed to Java action
 * 'AgentCommons.ChatContext_Create_ForAgent' do not match the expected
 * parameters and need to be refreshed."
 * Same shape, same fix: on the Java side the parameter is a plain
 * java.lang.String, so this action takes a string and hands it over. Two
 * independent modules hitting this in one session is the argument for teaching
 * mxcli to emit Microflows$MicroflowParameterValue rather than bridging it
 * per module.
 */
public class JA_ChatContext_CreateForAgent extends UserAction<IMendixObject>
{
	/** @deprecated use Agent.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Agent;
	private final agentcommons.proxies.Agent Agent;
	private final java.lang.String ActionMicroflow;

	public JA_ChatContext_CreateForAgent(
		IContext context,
		IMendixObject _agent,
		java.lang.String _actionMicroflow
	)
	{
		super(context);
		this.__Agent = _agent;
		this.Agent = _agent == null ? null : agentcommons.proxies.Agent.initialize(getContext(), _agent);
		this.ActionMicroflow = _actionMicroflow;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		// ContextObject and OverwritingDeployedModel are left null: this app has no
		// context entity, and the model comes from the agent's in-use version.
		return new agentcommons.actions.ChatContext_Create_ForAgent(
		        getContext(),
		        Agent.getMendixObject(),
		        ActionMicroflow,
		        null,
		        null
		).executeAction();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ChatContext_CreateForAgent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
