#!/bin/sh
# Originally generated by 'mxcli init'; edited to build mxcli from source. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: fetch mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~86 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script fetches it rather than
# skipping when it is absent.
#
# This project tracks ako/mxcli main rather than the mendixlabs nightly binary,
# so there is nothing to download: the binary is BUILT here. That needs Go, a
# JVM and network access, and takes ~3 minutes cold (~15s warm, thanks to the
# Go build cache). Pin a different commit/branch with MXCLI_REF.
set -e

MPR='MxcliChat.mpr'
MXCLI_REPO="${MXCLI_REPO:-https://github.com/ako/mxcli}"
MXCLI_REF="${MXCLI_REF:-main}"
# Pinned by mdl/grammar/Makefile; a generator/runtime mismatch yields a parser
# that does not compile.
ANTLR_VERSION=4.13.2
SRC="${MXCLI_SRC:-$HOME/.cache/mxcli-src}"

if [ ! -x ./mxcli ]; then
  echo "mxcli not found — building from ${MXCLI_REPO} (${MXCLI_REF})..."

  command -v go >/dev/null 2>&1 || { echo "Go toolchain required to build mxcli." >&2; exit 1; }
  command -v java >/dev/null 2>&1 || { echo "A JVM is required (ANTLR parser generation)." >&2; exit 1; }

  if [ -d "$SRC/.git" ]; then
    git -C "$SRC" fetch --depth 1 origin "$MXCLI_REF"
    git -C "$SRC" checkout -f FETCH_HEAD
  else
    rm -rf "$SRC"
    GIT_LFS_SKIP_SMUDGE=1 git clone --depth 1 --branch "$MXCLI_REF" "$MXCLI_REPO" "$SRC"
  fi

  # The generated ANTLR parser is not committed, so `make grammar` must run
  # first — which needs an `antlr4` launcher on PATH. antlr4-tools (pip) is the
  # documented route; the jar direct from Maven Central is fewer moving parts.
  jar="$SRC/.antlr/antlr-${ANTLR_VERSION}-complete.jar"
  if [ ! -f "$jar" ]; then
    mkdir -p "$SRC/.antlr"
    curl -fsSL -o "$jar" \
      "https://repo1.maven.org/maven2/org/antlr/antlr4/${ANTLR_VERSION}/antlr4-${ANTLR_VERSION}-complete.jar"
  fi
  mkdir -p "$SRC/.antlr/bin"
  printf '#!/bin/sh\nexec java -jar "%s" "$@"\n' "$jar" > "$SRC/.antlr/bin/antlr4"
  chmod +x "$SRC/.antlr/bin/antlr4"

  PATH="$SRC/.antlr/bin:$PATH" ANTLR4_TOOLS_ANTLR_VERSION="$ANTLR_VERSION" \
    make -C "$SRC" build
  cp "$SRC/bin/mxcli" ./mxcli
  chmod +x ./mxcli
  echo "Built mxcli from $(git -C "$SRC" rev-parse --short HEAD)"
fi

# Keep .ai-context/skills/ in step with this binary. The skills are embedded in
# mxcli and written once by 'mxcli init', so upgrading the binary used to leave
# yesterday's guidance in place with no warning — and an agent reads stale
# guidance with the same confidence as current guidance. Quiet when already
# current; never fatal, since a skills refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
